# Site settings
title: Baby on Board!
description: A blog about baby caring from a Nordic perspective
baseurl: "/will-jekyll-template" # the subpath of your site, e.g. /blog
url: "blog" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Annemarie
user_description: New mom
user_title: New mom
email: annemarie86@gmail.com
twitter_username: annemarie
github_username:  annemarie
gplus_username:  annemarie
disqus_username:  annemarie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
